### PR TITLE
1 log in

### PR DESCRIPTION
**Pull request by KolyaLovesMarlboro**
My Use case is fully finished and ready for merging.

### CODE REVIEW

**Comment by Masonhhhh** [comment]
Can u refactor all ur use cases by adding a login in front of it? it makes things clearer and gets rid of code smell. Like instead of interacter say loginInteracter

**Comment by KolyaLovesMarlboro** [comment]
All the required refactoring was done.

**Comment by KolyaLovesMarlboro** [comment]
Please, can I get a Review on my code? And in case everything is good, please approve merging with the main branch.

**Comment by Masonhhhh** [comment]
Good job! The use case is clean and all required features are fully given! I think you can merge it to the main branch.

**Review by Masonhhhh — APPROVED** [review]
ready to merge

**Pull request merged**
