### PR TITLE
6 filter look for course

### PR DESCRIPTION
**Pull request by Masonhhhh**
filterCourse completed, it works!

### CODE REVIEW

**Comment by KolyaLovesMarlboro** [comment]
please make sure you resolve the conflict before merging. Do not commit the files that are specific to your local build. For example folder .idea. Or .sav files, as they are automatically generated when the project runs.

**Comment by KolyaLovesMarlboro** [comment]
image
For now, tests are absent. Please make sure you test classes implemented by you. If you chose not to test some part of your code- indicate the reason for that in the documentation. Please also make use of JavaDoc, which will increase readability a lot.

**Comment by KolyaLovesMarlboro** [comment]
We fixed the Gradle build. So Mason needs to make only tests and the PR is ready to be merged with the main. Also figured out that the tests were not running because JUnit5 was not working.

**Review by Shawndavison26 — APPROVED** [review]
Everything looks good to merge onto main.

**Comment by KolyaLovesMarlboro** [comment]
The problem was that dataFill was main and it was not called inside the test module, so it was basically impossible to import courses. Also some of the tests were importing Junit 4 instead of Junit 5 that's why it was not working. I fixed it, now everything should work fine.

**Pull request merged**
